name: PR Visual Regression
on:
  workflow_run:
    workflows: [PR Build]
    types:
      - completed
jobs:
  pr-visual-regression:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Event
        id: get_pr_event
        uses: potiuk/get-workflow-origin@v1_1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          sourceRunId: ${{github.event.workflow_run.id}}
      - name: Cancel if PR doesn't target `main` branch
        if: ${{steps.get_pr_event.outputs.targetBranch != 'main'}}
        uses: andymckay/cancel-action@0.2
      - uses: haya14busa/action-workflow_run-status@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Download Storybook Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: storybook
          path: dist/storybook
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
      - name: Deploy Chromatic
        timeout-minutes: 5
        env:
          CHROMATIC_PROJECT_TOKEN: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
        run: npx chromatic --storybook-build-dir ./dist/storybook
